# Generated by Django 5.2.3 on 2025-07-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_borrowhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
        migrations.DeleteModel(
            name='BorrowHistory',
        ),
    ]
