# Generated by Django 5.2.3 on 2025-07-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_booktwo_delete_borrowhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='hehe'),
        ),
        migrations.AddField(
            model_name='booktwo',
            name='description',
            field=models.TextField(default='hehe'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author'),
        ),
        migrations.AlterField(
            model_name='booktwo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_twos', to='books.author'),
        ),
    ]
