# Generated by Django 5.2.3 on 2025-07-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_age_book_description_booktwo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='This is a well-written novel exploring deep human emotions and relationships.'),
        ),
        migrations.AlterField(
            model_name='booktwo',
            name='description',
            field=models.TextField(default='An insightful book with compelling narratives and thoughtful storytelling.'),
        ),
    ]
