# Generated by Django 5.2.3 on 2025-07-20 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_description_alter_booktwo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 20, 7, 59, 7, 817149, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 20, 7, 59, 11, 321142, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
