# Generated by Django 5.2.4 on 2025-07-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_author_created_at_book_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTwo',
        ),
    ]
